# Generated by Django 4.2.7 on 2024-02-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_car_owner_moto_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ammount',
            field=models.IntegerField(default=1000, verbose_name='цена'),
        ),
    ]
